export enum C {
  USER_LOGIN,
  MEDICO,
  PAZIENTE,
  PAZIENTI,
  PAZIENTE_SELEZIONATO,
  PROSSIMO_APPUNTAMENTO,
  ORARI_PRENOTAZIONE,
  APPUNTAMENTI,
  DATA_SELEZIONATA,
  RICETTE,
  //Utilita
  CARICAMENTO,
}
